[package]
name = "test-wrapper"
version = "0.1.0"
authors = ["David Pedersen <david.pdrsn@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
test-wrapper-code-gen = { path = "../test-wrapper-code-gen", version = "0.1.0" }
inventory = "0.1"
